config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'categories/index'
    get 'categories/new'
    get 'categories/create'
    resources :categories, only: [:index, :new, :create]
  end

  get 'about/index'
  root to: 'products#index'
  get '/about', to: 'about#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :catagories, only: [:new, :create, :index]

  end

 get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

  

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  http_basic_authenticate_with name: ENV["ADMIN_USERNAME"], password: ENV["ADMIN_PASSWORD"]
  def show
    @products_count = Product.count
    @categories_count = Category.count
  end
end

app/views/admin/dashboard/show.html.erb
<h1>Admin Dashboard:</h1>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
             <h5 class="card-title">Products</h5>
          <p class="card-text"><%= @products_count %> products in the database</p>
          <%= link_to "View Products", admin_products_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Categories</h5>
          <p class="card-text"><%= @categories_count %> categories in the database</p>
                    <%= link_to "View Categories", admin_categories_path, class: "btn btn-primary" %>

        </div>
        </div>
    </div>
  </div>
</div>